name: Weblocks Official Site

languages: ['ja', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images']
parallel_localization: true
lang_from_path: true

url: "https://weblocks.github.io"

plugins:
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-sitemap
